import { AudioEngine } from './audio-engine.js';
import { defaultAudioLabConfig, normalizeAudioLabConfig, pitchRatio, effectActive, nextPlayhead, layerIntervals } from './audio-lab-utils.js';
import { putAudioAsset, listAudioAssets, getAudioAsset, deleteAudioAsset, putAudioProject, listAudioProjects, deleteAudioProject } from './audio-lab-store.js';

const fmt = seconds => `${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}.${Math.floor(seconds%1*10)}`;

export class AudioLab {
  constructor(onPlay){this.onPlay=onPlay;this.host=new AudioEngine();this.config=defaultAudioLabConfig();this.assets=[];this.projects=[];this.sources=new Set();this.position=0;}
  get playing(){return !!this.active;}
  setVolume(value){this.host.setVolume(value);}
  message(text){const el=this.root?.querySelector('#audio-lab-message');if(el)el.textContent=text;}
  async ready(){await this.host.ensureContext();this.host.playing=true;this.host.setVolume(this.host.volume);}
  render(root){
    this.root=root;this.setVolume(document.querySelector('#master-volume')?.value??this.host.volume);
    root.innerHTML=`<div class="studio-heading"><div><small>08 / AUDIO LAB</small><h1>音檔合成與狀態工作台</h1></div><span class="tag">IndexedDB LOCAL</span></div>
    <section class="audio-lab-grid"><aside class="panel audio-assets"><div class="tool-title"><strong>本機音檔</strong><small>不會上傳伺服器</small></div><label id="audio-drop" class="audio-drop">拖入音檔或點擊選擇<input id="audio-upload" type="file" accept="audio/*" multiple></label><div id="audio-assets"></div></aside>
    <div class="audio-editor"><section class="panel audio-timeline"><div class="tool-title"><div><small id="audio-file-meta">NO AUDIO</small><h2 id="audio-file-name">先加入一個音檔</h2></div><output id="audio-position">0:00.0</output></div><div class="wave-wrap"><canvas id="audio-waveform" aria-label="音訊波形"></canvas><i id="clip-region"></i><b id="effect-region"></b><span id="playhead"></span></div><div class="region-controls"><label>片段開始<input data-region="start" type="number" min="0" step=".01"></label><label>片段結束<input data-region="end" type="number" min="0" step=".01"></label><label>FX 開始<input data-region="effectStart" type="number" min="0" step=".01"></label><label>FX 結束<input data-region="effectEnd" type="number" min="0" step=".01"></label></div><div class="audio-lab-transport"><button id="audio-lab-play" class="primary">播放處理結果</button><button id="audio-lab-stop">停止</button><button id="freeze-here">凍結目前位置</button><label><input data-config="loop" type="checkbox">循環</label></div></section>
    <section class="panel audio-process"><div class="tool-title"><strong>播放與後處理</strong><small>只作用在橘色 FX 區段</small></div><div class="audio-control-grid">
      ${this.range('speed','速度（保留音高）',.05,2,.01,'×')}${this.range('key','Key',-12,12,1,' st')}${this.range('fadeIn','淡入',0,10,.05,' s')}${this.range('fadeOut','淡出',0,10,.05,' s')}
      ${this.range('eqLow','EQ Low',-12,12,.5,' dB')}${this.range('eqMid','EQ Mid',-12,12,.5,' dB')}${this.range('eqHigh','EQ High',-12,12,.5,' dB')}
      ${this.range('delay','Delay',0,.8,.01,'')}${this.range('reverb','Reverb',0,.9,.01,'')}${this.range('spatial','3D Surround',0,1,.01,'')}
    </div><div class="process-toggles"><label><input data-config="reverse" type="checkbox"> Reverse 倒帶</label><label><input data-config="telephone" type="checkbox"> Telephone / Radio</label><label><input data-config="vinyl" type="checkbox"> Vinyl / Lo-Fi Degradation</label></div></section>
    <section class="audio-lab-modes"><div class="panel mode-card"><label><input data-config="granular" type="checkbox"><strong>Grains 微粒</strong></label>${this.range('grainSize','粒徑',.03,1.5,.01,' s')}${this.range('density','密度',4,40,1,'/s')}<p>重疊微小碎片，以密度與粒徑改變科技感。</p></div><div class="panel mode-card"><label><input data-config="layering" type="checkbox"><strong>Vocal Layering & Harmonization</strong></label>${this.range('layers','疊加軌數',1,12,1,'')}<p>主音、高三／五度、低音與耳語感層次。</p></div><div class="panel mode-card"><label><input data-config="freeze" type="checkbox"><strong>Spectral Freeze / Paulstretch</strong></label><label><input data-config="stretch" type="checkbox"> Extreme Stretch</label><p>凍結指定瞬間，或用長微粒做即時 Paulstretch 近似。</p></div></section>
    <section class="panel audio-projects"><div class="tool-title"><strong>本機處理設定</strong><small>音檔與參數均存於此瀏覽器</small></div><form id="save-audio-project"><input name="name" maxlength="100" placeholder="設定名稱" required><button>儲存設定</button></form><div id="audio-project-list"></div><p id="audio-lab-message" role="status"></p></section></div></section>`;
    this.bind();this.refreshCollections();
  }
  range(key,label,min,max,step,unit){return `<label class="audio-control"><span>${label}<output data-output="${key}"></output></span><input data-config="${key}" type="range" min="${min}" max="${max}" step="${step}" data-unit="${unit}"></label>`;}
  bind(){
    const root=this.root,upload=root.querySelector('#audio-upload'),drop=root.querySelector('#audio-drop');upload.onchange=()=>this.upload(upload.files);drop.ondragover=e=>{e.preventDefault();drop.classList.add('active');};drop.ondragleave=()=>drop.classList.remove('active');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('active');this.upload(e.dataTransfer.files);};
    root.querySelectorAll('[data-config]').forEach(input=>{input.oninput=()=>{this.config[input.dataset.config]=input.type==='checkbox'?input.checked:Number(input.value);this.syncControls(false);};});
    root.querySelectorAll('[data-region]').forEach(input=>{input.onchange=()=>{this.config[input.dataset.region]=Number(input.value);this.config=normalizeAudioLabConfig(this.config,this.buffer?.duration||1);this.syncControls();};});
    root.querySelector('#audio-lab-play').onclick=()=>this.play();root.querySelector('#audio-lab-stop').onclick=()=>this.stop();root.querySelector('#freeze-here').onclick=()=>{this.config.freezeAt=Math.max(this.config.start,Math.min(this.config.end,this.position||this.config.start));this.config.freeze=true;this.syncControls();this.message(`已將 ${fmt(this.config.freezeAt)} 設為 Freeze 點。`);};
    root.querySelector('#audio-waveform').onclick=e=>{if(!this.buffer)return;const rect=e.currentTarget.getBoundingClientRect();this.config.freezeAt=(e.clientX-rect.left)/rect.width*this.buffer.duration;this.position=this.config.freezeAt;this.syncTimeline();};
    root.querySelector('#save-audio-project').onsubmit=e=>{e.preventDefault();this.saveProject(e.target.elements.name.value.trim());};this.syncControls();
  }
  async upload(files){for(const file of files){if(!file.type.startsWith('audio/'))continue;try{await putAudioAsset(file);}catch(error){this.message(`無法保存 ${file.name}：${error.message}`);}}await this.refreshCollections();if(this.assets[0])await this.selectAsset(this.assets[0].id);}
  async refreshCollections(){try{[this.assets,this.projects]=await Promise.all([listAudioAssets(),listAudioProjects()]);this.paintAssets();this.paintProjects();}catch(error){this.message(`本機資料庫無法使用：${error.message}`);}}
  paintAssets(){const host=this.root.querySelector('#audio-assets');host.replaceChildren();for(const asset of this.assets){const row=document.createElement('div');row.className='audio-asset-row';const load=document.createElement('button');load.textContent=asset.name;load.classList.toggle('active',asset.id===this.selectedId);load.onclick=()=>this.selectAsset(asset.id);const remove=document.createElement('button');remove.textContent='×';remove.ariaLabel=`移除 ${asset.name}`;remove.onclick=async()=>{if(asset.id===this.selectedId){this.stop();this.selectedId=null;this.buffer=null;}await deleteAudioAsset(asset.id);await this.refreshCollections();};row.append(load,remove);host.append(row);}if(!host.children.length)host.textContent='尚未保存音檔';}
  async selectAsset(id){this.stop();try{await this.ready();const asset=await getAudioAsset(id);if(!asset)throw new Error('找不到音檔');this.buffer=await this.host.context.decodeAudioData(await asset.blob.arrayBuffer());this.reverseBuffer=this.reverseAudio(this.buffer);this.selectedId=id;this.selectedAsset=asset;this.config=normalizeAudioLabConfig(defaultAudioLabConfig(),this.buffer.duration);this.position=this.config.start;this.paintAssets();this.syncControls();this.drawWaveform();}catch(error){this.message(`音檔無法解碼：${error.message}`);}}
  reverseAudio(buffer){const reversed=this.host.context.createBuffer(buffer.numberOfChannels,buffer.length,buffer.sampleRate);for(let channel=0;channel<buffer.numberOfChannels;channel++){const from=buffer.getChannelData(channel),to=reversed.getChannelData(channel);for(let i=0;i<from.length;i++)to[i]=from[from.length-1-i];}return reversed;}
  syncControls(updateInputs=true){if(this.buffer)this.config=normalizeAudioLabConfig(this.config,this.buffer.duration);if(updateInputs){this.root.querySelectorAll('[data-config]').forEach(input=>{const value=this.config[input.dataset.config];if(input.type==='checkbox')input.checked=!!value;else input.value=value;});this.root.querySelectorAll('[data-region]').forEach(input=>{input.max=this.buffer?.duration||0;input.value=this.config[input.dataset.region]||0;});}this.root.querySelectorAll('[data-output]').forEach(output=>{const input=this.root.querySelector(`[data-config="${output.dataset.output}"]`),unit=input?.dataset.unit||'';output.textContent=`${this.config[output.dataset.output]}${unit}`;});this.syncTimeline();}
  syncTimeline(){if(!this.root?.querySelector('#audio-file-name'))return;const duration=this.buffer?.duration||1,name=this.root.querySelector('#audio-file-name'),meta=this.root.querySelector('#audio-file-meta');name.textContent=this.selectedAsset?.name||'先加入一個音檔';meta.textContent=this.buffer?`${fmt(duration)} · ${(this.selectedAsset.size/1048576).toFixed(1)} MB`:'NO AUDIO';const clip=this.root.querySelector('#clip-region'),effect=this.root.querySelector('#effect-region'),playhead=this.root.querySelector('#playhead');clip.style.left=`${this.config.start/duration*100}%`;clip.style.width=`${(this.config.end-this.config.start)/duration*100}%`;effect.style.left=`${this.config.effectStart/duration*100}%`;effect.style.width=`${(this.config.effectEnd-this.config.effectStart)/duration*100}%`;playhead.style.left=`${(this.position||0)/duration*100}%`;this.root.querySelector('#audio-position').textContent=fmt(this.position||0);}
  drawWaveform(){const canvas=this.root.querySelector('#audio-waveform'),ctx=canvas.getContext('2d'),width=Math.max(600,canvas.clientWidth*devicePixelRatio),height=150*devicePixelRatio;canvas.width=width;canvas.height=height;ctx.clearRect(0,0,width,height);ctx.strokeStyle='#13231f';ctx.globalAlpha=.55;ctx.beginPath();const data=this.buffer.getChannelData(0),step=Math.max(1,Math.floor(data.length/width));for(let x=0;x<width;x++){let min=1,max=-1;for(let i=0;i<step;i++){const value=data[x*step+i]||0;min=Math.min(min,value);max=Math.max(max,value);}ctx.moveTo(x,(1+min)*height/2);ctx.lineTo(x,(1+max)*height/2);}ctx.stroke();this.syncTimeline();}
  async play(){if(!this.buffer){this.message('請先加入並選擇音檔。');return;}this.stop(false);await this.ready();this.config=normalizeAudioLabConfig(this.config,this.buffer.duration);if(this.position<this.config.start||this.position>=this.config.end)this.position=this.config.start;this.prepareGraph();this.active=true;this.nextTime=this.host.context.currentTime+.04;this.playhead=this.position;this.ending=false;this.schedule();this.scheduler=setInterval(()=>this.schedule(),25);this.onPlay(true);this.paintPlaying();}
  prepareGraph(){const ctx=this.host.context,c=this.config;this.dryBus=ctx.createGain();this.processInput=ctx.createGain();const low=ctx.createBiquadFilter(),mid=ctx.createBiquadFilter(),high=ctx.createBiquadFilter(),phoneLow=ctx.createBiquadFilter(),phoneHigh=ctx.createBiquadFilter(),pan=ctx.createStereoPanner(),direct=ctx.createGain(),delay=ctx.createDelay(2),feedback=ctx.createGain(),delayWet=ctx.createGain(),convolver=ctx.createConvolver(),reverbWet=ctx.createGain();low.type='lowshelf';low.frequency.value=180;low.gain.value=c.eqLow;mid.type='peaking';mid.frequency.value=1200;mid.Q.value=.8;mid.gain.value=c.eqMid;high.type='highshelf';high.frequency.value=5200;high.gain.value=c.eqHigh;phoneHigh.type='highpass';phoneHigh.frequency.value=c.telephone?320:20;phoneLow.type='lowpass';phoneLow.frequency.value=c.telephone?3400:20000;delay.delayTime.value=.16+c.delay*.55;feedback.gain.value=c.delay*.58;delayWet.gain.value=c.delay*.65;convolver.buffer=this.impulse(1.2+c.reverb*2.8);reverbWet.gain.value=c.reverb*.55;this.dryBus.connect(this.host.master);this.processInput.connect(low).connect(mid).connect(high).connect(phoneHigh).connect(phoneLow).connect(pan);pan.connect(direct).connect(this.host.master);pan.connect(delay).connect(delayWet).connect(this.host.master);delay.connect(feedback).connect(delay);pan.connect(convolver).connect(reverbWet).connect(this.host.master);this.processPan=pan;this.graphNodes=[this.dryBus,this.processInput,low,mid,high,phoneHigh,phoneLow,pan,direct,delay,feedback,delayWet,convolver,reverbWet];if(c.vinyl)this.startVinyl();}
  impulse(seconds){const ctx=this.host.context,length=Math.ceil(ctx.sampleRate*seconds),buffer=ctx.createBuffer(2,length,ctx.sampleRate);for(let channel=0;channel<2;channel++){const data=buffer.getChannelData(channel);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*(1-i/length)**2.4;}return buffer;}
  startVinyl(){const ctx=this.host.context,length=ctx.sampleRate*2,buffer=ctx.createBuffer(1,length,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=Math.random()<.0025?(Math.random()*2-1)*.8:(Math.random()*2-1)*.015;const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();source.buffer=buffer;source.loop=true;filter.type='bandpass';filter.frequency.value=2600;filter.Q.value=.35;gain.gain.value=.055;source.connect(filter).connect(gain).connect(this.processInput);source.start();this.vinylSource=source;this.graphNodes.push(source,filter,gain);}
  schedule(){if(!this.active||this.ending)return;const ctx=this.host.context,c=this.config,hop=1/(c.granular||c.stretch?c.density:20),window=ctx.currentTime+.24;while(this.nextTime<window){if(!c.freeze&&this.playhead>=c.end){if(c.loop)this.playhead=c.start;else{this.ending=true;setTimeout(()=>this.stop(false),Math.max(0,(this.nextTime-ctx.currentTime)*1000));break;}}this.scheduleGrain(this.nextTime,this.playhead,hop);this.nextTime+=hop;this.playhead=nextPlayhead(this.playhead,hop,c);}this.position=Math.min(c.end,this.playhead);this.syncTimeline();}
  scheduleGrain(when,position,hop){const c=this.config,baseSize=c.stretch?Math.max(.7,c.grainSize):c.granular?c.grainSize:.16,intervals=c.layering?layerIntervals(c.layers):[0],active=effectActive(position,c),destination=active?this.processInput:this.dryBus,fadeIn=c.fadeIn?Math.min(1,(position-c.start)/c.fadeIn):1,fadeOut=c.fadeOut?Math.min(1,(c.end-position)/c.fadeOut):1,fade=Math.max(.001,Math.min(fadeIn,fadeOut)),wow=c.vinyl?Math.sin(position*4.3)*.003:0;
    intervals.forEach((semitones,index)=>{const ratio=pitchRatio(c.key+semitones),source=this.host.context.createBufferSource(),gain=this.host.context.createGain(),size=baseSize*(index?1.06:1),sourceDuration=Math.min(size*ratio,this.buffer.duration),jitter=c.freeze?(Math.random()-.5)*Math.min(.08,size*.3):c.stretch?(Math.random()-.5)*.15:0,original=Math.max(0,Math.min(this.buffer.duration-sourceDuration,(c.freeze?c.freezeAt:position)+jitter+wow)),offset=c.reverse?Math.max(0,this.buffer.duration-original-sourceDuration):original,level=.62/Math.sqrt(intervals.length);source.buffer=c.reverse?this.reverseBuffer:this.buffer;source.playbackRate.value=ratio;gain.gain.setValueAtTime(.0001,when);gain.gain.linearRampToValueAtTime(level*fade,when+size*.22);gain.gain.setValueAtTime(level*fade,when+size*.72);gain.gain.exponentialRampToValueAtTime(.0001,when+size);source.connect(gain).connect(destination);source.start(when,offset,sourceDuration);source.stop(when+size+.03);this.sources.add(source);source.onended=()=>{this.sources.delete(source);source.disconnect();gain.disconnect();};});
    if(active&&c.spatial)this.processPan.pan.setTargetAtTime(Math.sin(position*1.7)*c.spatial,when,.04);
  }
  stop(reset=true){clearInterval(this.scheduler);this.scheduler=null;this.active=false;for(const source of this.sources){try{source.stop();}catch{}}this.sources.clear();try{this.vinylSource?.stop();}catch{}this.vinylSource=null;this.graphNodes?.forEach(node=>{try{node.disconnect();}catch{}});this.graphNodes=[];if(reset&&this.buffer)this.position=this.config.start;this.onPlay(false);this.paintPlaying();this.syncTimeline();}
  paintPlaying(){const button=this.root?.querySelector('#audio-lab-play');if(button)button.textContent=this.active?'重新播放':'播放處理結果';}
  async saveProject(name){if(!this.selectedId){this.message('請先選擇音檔。');return;}const project={id:crypto.randomUUID(),name:name||'未命名處理',assetId:this.selectedId,config:structuredClone(this.config),createdAt:new Date().toISOString()};await putAudioProject(project);this.message('音檔設定已保存於瀏覽器。');await this.refreshCollections();}
  paintProjects(){const host=this.root.querySelector('#audio-project-list');host.replaceChildren();for(const project of this.projects){const row=document.createElement('div');row.className='audio-project-row';const load=document.createElement('button');load.textContent=project.name;load.onclick=async()=>{await this.selectAsset(project.assetId);this.config=normalizeAudioLabConfig(project.config,this.buffer.duration);this.position=this.config.start;this.syncControls();};const remove=document.createElement('button');remove.textContent='移除';remove.onclick=async()=>{await deleteAudioProject(project.id);await this.refreshCollections();};row.append(load,remove);host.append(row);}if(!host.children.length)host.textContent='尚未保存處理設定';}
  unmount(){this.stop();}
}
